env:
  # Telegram
  TG_CHAT: "@Kartik_dumps"
  TG_TOKEN: ENCRYPTED[!da89ec39548c2760742f7e804314a1d3eb2b25ee5d894b8e32852cfc6bf2ab40477ba720d127f44088b365fdfb5a287a!]
  
  # Gitlab
  PUSH_TO_GITLAB: true
  GITLAB_GROUP: Dumper
  GITLAB_TOKEN: ENCRYPTED[!a47f527e03e517ac747c672b11625ba8c1b642ff55514de4610ce687c8ecb3b20c0a6307ba93b62ae6d59ff972278f67!]
  GITLAB_INSTANCE: www.gitgud.io
  
  # Private SSH Key
  PRIV_SSH_KEY: ENCRYPTED[!46f196ad59d78bede0cd384597301a1e8dde0aad8b952b99bdf9278730146634a12e75e6d21986ce23718807fafd3688!]

task:
  name: "Firmware Dump by Dumper"
  only_if: $CIRRUS_REPO_OWNER == 'Kartik-91'
  skip: $CIRRUS_BRANCH == 'main'
  auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa $GITLAB_INSTANCE >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > /root/.ssh/id_rsa
      - cat /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "Kartikbanwala"
      - git config --global user.email "kartikbanwala@proton.me"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - echo "$GITLAB_INSTANCE" > .gitlab_instance
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)
